{
 "title": "Snowflake Proxy",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Served People",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "served_people", "legendFormat": "{{time}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(dockerstats_cpu_usage_ratio{name=\"snowflake-proxy\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Served People (Last 24H)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "served_people{time=\"Last 24h\"}",
     "legendFormat": "{{time}}"
    }
   ]
  },
  {
   "title": "Downloaded Data",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "download_gb", "legendFormat": "{{time}}" }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(dockerstats_memory_usage_bytes{name=\"snowflake-proxy\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downloaded Data (Last 24H)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "download_gb{time=\"Last 24h\"}",
     "legendFormat": "{{time}}"
    }
   ]
  },
  {
   "title": "Uploaded Data",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upload_gb", "legendFormat": "{{time}}" }
   ]
  },
  {
   "title": "Uploaded Data (Last 24H)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "upload_gb{time=\"Last 24h\"}",
     "legendFormat": "{{time}}"
    }
   ]
  }
 ]
}